[2024-05-07 15:01:25,704] 96 werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8000
 * Running on http://192.168.1.9:8000
[2024-05-07 15:01:25,705] 96 werkzeug - INFO - [33mPress CTRL+C to quit[0m
[2024-05-07 15:01:29,257] 96 werkzeug - INFO - 127.0.0.1 - - [07/May/2024 15:01:29] "GET / HTTP/1.1" 200 -
[2024-05-07 15:01:34,283] 96 werkzeug - INFO - 127.0.0.1 - - [07/May/2024 15:01:34] "GET /predict HTTP/1.1" 200 -
[2024-05-07 15:01:44,528] 67 root - INFO - Dataframe Gathered
[2024-05-07 15:01:44,528] 54 root - INFO - Exception Occured in load_object function utils
[2024-05-07 15:01:44,529] 1414 app - ERROR - Exception on /predict [POST]
Traceback (most recent call last):
  File "C:\Users\nisha\PycharmProjects\pythonProject1\Blackcoffer\MLOps_Projects\MLops_demo\src\utils\utils.py", line 51, in load_object
    with open(file_path, 'rb') as file_obj:
         ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts\\preprocessor.pkl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nisha\PycharmProjects\pythonProject1\Blackcoffer\MLOps_Projects\MLops_demo\src\pipeline\prediction_pipeline.py", line 19, in predict
    preprocessor = load_object(preprocessor_path)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nisha\PycharmProjects\pythonProject1\Blackcoffer\MLOps_Projects\MLops_demo\src\utils\utils.py", line 55, in load_object
    raise customexception(e, sys)
src.exception.exception.customexception: Error occured in python script name [C:\Users\nisha\PycharmProjects\pythonProject1\Blackcoffer\MLOps_Projects\MLops_demo\src\utils\utils.py] line number [51] error message [[Errno 2] No such file or directory: 'artifacts\\preprocessor.pkl']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nisha\PycharmProjects\pythonProject1\venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nisha\PycharmProjects\pythonProject1\venv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nisha\PycharmProjects\pythonProject1\venv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nisha\PycharmProjects\pythonProject1\venv\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nisha\PycharmProjects\pythonProject1\Blackcoffer\MLOps_Projects\MLops_demo\app.py", line 33, in predict_datapoint
    pred = predict_pipeline.predict(final_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nisha\PycharmProjects\pythonProject1\Blackcoffer\MLOps_Projects\MLops_demo\src\pipeline\prediction_pipeline.py", line 28, in predict
    raise customexception(e, sys)
src.exception.exception.customexception: Error occured in python script name [C:\Users\nisha\PycharmProjects\pythonProject1\Blackcoffer\MLOps_Projects\MLops_demo\src\pipeline\prediction_pipeline.py] line number [19] error message [Error occured in python script name [C:\Users\nisha\PycharmProjects\pythonProject1\Blackcoffer\MLOps_Projects\MLops_demo\src\utils\utils.py] line number [51] error message [[Errno 2] No such file or directory: 'artifacts\\preprocessor.pkl']]
[2024-05-07 15:01:44,539] 96 werkzeug - INFO - 127.0.0.1 - - [07/May/2024 15:01:44] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -
[2024-05-07 15:03:30,586] 67 root - INFO - Dataframe Gathered
[2024-05-07 15:03:30,977] 96 werkzeug - INFO - 127.0.0.1 - - [07/May/2024 15:03:30] "POST /predict HTTP/1.1" 200 -
